### ISSUE TITLE
Faltan datos

### ISSUE THREAD

**Issue by LautaroRomero21** [pdepmartestm/bienvenida-2023-gastonorqueda#1]
Hola Gaston. te falto poner tu legajo y una foto personal tuya

**Comment by gastonorqueda** [comment]
Gracias, es verdad, ahi agrego

**Comment by lspigariol** [comment]
No hace falta el legajo. 
Si preferis poner una imagen simbólica en vez de una foto, tambien vale

**Comment by gastonorqueda** [comment]
Genial, con el gif que coloque es suficiente?
